name: bellevie
description: BelleVie Global Health Services
version: 1.0.2+3
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  http: ^1.2.2
  country_picker: ^2.0.27
  shared_preferences: ^2.5.5
  image_picker: ^1.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/banners/appicon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/banners/
    - assets/images/core_four/
    - assets/images/special doctors/
    
